apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: grafana-claim
spec:
    resources:
        requests:
            storage: 15Gi
    accessModes:
        - ReadWriteOnce
    storageClassName: standard
